### ISSUE TITLE
If the size of a code block is the same a the usb buffer PROGRAM_COMPLETE is not called

### ISSUE THREAD

**Issue by mickeprag** [ApertureLabsLtd/mphidflash#18]
See this example:

    USB HID device found: 28672 bytes free
    Device family: PIC18

    Erasing...
    Writing hex file 'firmware.hex':Address: 00001000  Len 6
    Writing
    Completing
    Address: 00001008  Len 12
    Writing
    Completing
    Address: 00001018  Len 56
    Writing
    Address: 00005410  Len 56
    Writing
    Address: 00005448  Len 56
    Writing

After writing address 0x1018 it should have written "Completing" but did not since the len was 56 (which is the same as the buffer).

**Comment by AdamLaurie** [comment]
"completing" is only required for short blocks and is explicitly for blocks < 56:

if((ERR_NONE == (status = usbWrite(64,0))) && (len < 56))

what is the error you're trying to address?

**Comment by mickeprag** [comment]
The firmware I am trying to flash seems to write successfully but when mphidflash verify the written data it fails.
When I read the data back (using a PicKit 3) I can see that the block at 0x1018 is written but no more data after that.

At 0x1018 there is a block of exactly 56 bytes. After this block the next data is not until address 0x5410. My guess was that when "jumping" in memory a "completing" signal must be sent.

I modified mphidflash to issue a PROGRAM_COMPLETE after this block and then it worked fine to flash the firmware.

**Comment by mickeprag** [comment]
This issue seems very similar (if not the same) as #9

**Comment by AdamLaurie** [comment]
OK, I guess the fix is to send always send a PROGRAM_COMPLETE if the block is the last one in that section?

**Comment by mickeprag** [comment]
Yes, I believe so. I tried to implement this but was unable to figure out when the block is the last one in the section.

**Comment by AdamLaurie** [comment]
Take a look around line 315 of hex.c - I think if you call  issueBlock with a length of 0 when appropriate then that will flush the data. I would try this myself but it's probably simpler if you do it as you're already set up with appropriate hex image etc.

**Comment by mickeprag** [comment]
Issuing the command is no problem. It's figuring out "when appropriate" I couldn't do. Currenlty I have added this patch and it works:

    diff --git a/hex.c b/hex.c
    index 59ff6d7..56dc289 100644
    --- a/hex.c
    +++ b/hex.c
    @@ -331,6 +331,11 @@ ErrorCode hexWrite(const char verify)
     	        if(sizeof(hexBuf) == bufLen) {
     	          if(ERR_NONE != (status = issueBlock(addrSave,bufLen,pass)))
     	            return status;
    +	          if (i+2 == end) {
    +	            DEBUGMSG("Completing");
    +	            usbBuf[0] = PROGRAM_COMPLETE;
    +	            if(ERR_NONE != (status = usbWrite(1,0))) return status;
    +	          }
     	          bufLen = 0;
     	        }
 
It's probably issuing the command more often than needed so perhaps you want it "prettier"?

**Comment by AdamLaurie** [comment]
Right, but my reading of the section around 315 is that it only gets activated when it's starting a write of a new section (fulfilling the "appropriate"), so it flushes the remaining data from the last. It should be easy to add a force of a 0 length write if the final block was exactly 56 bytes. Again, not easy for me to test I've read this right...

**Comment by mickeprag** [comment]
How do I figure out if "the final block was exactly 56 bytes" here? bufLen resets to 0 after last call to issueBlock. Which variable should I check?

**Comment by AdamLaurie** [comment]
Test bufLen == 56 just before it resets to 0?

**Comment by AdamLaurie** [comment]
Hopefully now sorted.
